# Generated by Django 4.2.3 on 2023-07-10 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('detection_count', models.CharField(max_length=50)),
                ('risk_level', models.CharField(max_length=50)),
                ('md5', models.CharField(max_length=32)),
                ('sha256', models.CharField(max_length=64)),
                ('sha1', models.CharField(max_length=40)),
                ('content_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LLMAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_id', models.IntegerField()),
                ('version', models.CharField(max_length=50)),
                ('result', models.TextField()),
                ('time', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('tokenizer', models.CharField(max_length=50)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoAudit.file')),
            ],
        ),
        migrations.CreateModel(
            name='ClamAVAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('virus_type', models.TextField()),
                ('is_infected', models.CharField(max_length=50)),
                ('known_viruses', models.CharField(max_length=50)),
                ('engine_version', models.CharField(max_length=50)),
                ('data_scanned', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoAudit.file')),
            ],
        ),
    ]
